/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Jugador;
import civitas.JugadorEspeculador;
import civitas.CasillaCalle;
import java.util.ArrayList;
/**
 *
 * @author albertollamasgonzalez
 */
public class JugadorPanel extends javax.swing.JPanel {

    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombre = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        LabelSaldo = new javax.swing.JLabel();
        FieldSaldo = new javax.swing.JTextField();
        LabelEspeculador = new javax.swing.JLabel();
        FieldEspeculador = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        LabelNombre.setText("Nombre");
        add(LabelNombre);

        FieldNombre.setEditable(false);
        FieldNombre.setText("nombre");
        FieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNombreActionPerformed(evt);
            }
        });
        add(FieldNombre);

        LabelSaldo.setText("Saldo");
        add(LabelSaldo);

        FieldSaldo.setEditable(false);
        FieldSaldo.setText("saldo");
        add(FieldSaldo);

        LabelEspeculador.setText("Especulador");
        add(LabelEspeculador);

        FieldEspeculador.setEditable(false);
        FieldEspeculador.setText("especulador");
        add(FieldEspeculador);

        propiedadesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNombreActionPerformed
    
    public void setJugador(Jugador j){
        this.jugador = j;
        String especulador;
        especulador = (this.jugador.isEspeculador() ? "true" : "false");
        this.FieldNombre.setText(this.jugador.getNombre());
        this.FieldSaldo.setText(Float.toString(this.jugador.getSaldo()));
        this.FieldEspeculador.setText(especulador);
        
        this.rellenaPropiedades(this.jugador.getPropiedades());
        repaint();
    }
    
     private void rellenaPropiedades (ArrayList<CasillaCalle> lista) {
               // Se elimina la información antigua
               propiedadesPanel.removeAll();
               // Se recorre la lista de propiedades para ir creando sus vistasindividuales y añadirlas al panel
               for (CasillaCalle t : lista) {
                   PropiedadPanel vistaPropiedad = new PropiedadPanel();
                   vistaPropiedad.setPropiedad(t);
                   propiedadesPanel.add(vistaPropiedad);
                   vistaPropiedad.setVisible(true);
                }
               
               // Se fuerza la actualización visual del panel propiedades y del panel del jugador
               repaint();
               revalidate();
    }
    private Jugador jugador;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldEspeculador;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JTextField FieldSaldo;
    private javax.swing.JLabel LabelEspeculador;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JPanel propiedadesPanel;
    // End of variables declaration//GEN-END:variables
}
