/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CasillaCalle;
/**
 *
 * @author albertollamasgonzalez
 */
public class PropiedadPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombrePropiedad = new javax.swing.JLabel();
        labelNumCasas = new javax.swing.JLabel();
        labelNumHoteles = new javax.swing.JLabel();
        fieldNombrePropiedad = new javax.swing.JTextField();
        fieldNumCasas = new javax.swing.JTextField();
        fieldNumHoteles = new javax.swing.JTextField();

        labelNombrePropiedad.setText("Nombre Propiedad:");

        labelNumCasas.setText("Numero de casas");

        labelNumHoteles.setText("Numero de hoteles");

        fieldNombrePropiedad.setEditable(false);
        fieldNombrePropiedad.setText("nombreProp");

        fieldNumCasas.setEditable(false);
        fieldNumCasas.setText("0");
        fieldNumCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumCasasActionPerformed(evt);
            }
        });

        fieldNumHoteles.setEditable(false);
        fieldNumHoteles.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNumHoteles)
                        .addGap(18, 18, 18)
                        .addComponent(fieldNumHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombrePropiedad)
                            .addComponent(labelNumCasas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNumCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNombrePropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombrePropiedad)
                    .addComponent(fieldNombrePropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumCasas)
                    .addComponent(fieldNumCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumHoteles)
                    .addComponent(fieldNumHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNumCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumCasasActionPerformed
    public void setPropiedad(CasillaCalle c){
        this.tituloPropiedad = c;   
        this.fieldNombrePropiedad.setText(this.tituloPropiedad.getNombre());
        this.fieldNumCasas.setText(Integer.toString(tituloPropiedad.getNumCasas()));
        this.fieldNumHoteles.setText(Integer.toString(tituloPropiedad.getNumHoteles()));
        
        repaint();
    }
    private CasillaCalle tituloPropiedad;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldNombrePropiedad;
    private javax.swing.JTextField fieldNumCasas;
    private javax.swing.JTextField fieldNumHoteles;
    private javax.swing.JLabel labelNombrePropiedad;
    private javax.swing.JLabel labelNumCasas;
    private javax.swing.JLabel labelNumHoteles;
    // End of variables declaration//GEN-END:variables
}
